// Auto-generated by scripts/download-sdk.js. Do NOT edit manually.
// Ensure window exists (for Node-based bundler pre-bundling environments)
const g = (typeof globalThis !== 'undefined' ? globalThis : (typeof global !== 'undefined' ? global : this));
if (typeof g.window === 'undefined') g.window = g;

// Require underlying UMD script (it assigns window.wx / window.jWeixin)
require('./lib/1.6.0/index.js');

// Retrieve the global export placed by the SDK
const wx = g.wx || g.jWeixin;

// Fallback: if still missing, export an empty object to avoid crashes
const exported = wx || {};

module.exports = exported;
Object.defineProperty(module.exports, '__esModule', { value: true });
Object.defineProperty(module.exports, 'default', { enumerable: false, value: exported });
